# Generated by Django 2.2 on 2020-12-22 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_questionchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='survey.QuestionChoice', verbose_name='Question choice'),
        ),
    ]
